### ISSUE TITLE
Plugin Not Working For Some Reason

### ISSUE THREAD

**Issue by ghost** [Justin42/Salesmania#7]
For some reason when I try to make an auction on the server it doesn't work it says "Auctions are disabled in this world" and I've setup all of the ranks and worlds for example my players play in the Wilderness world. Here is my Config:

``` yaml
Main:
  defaultLocale: english
  availableLocale:
  - english
  - french
  - portuguese
Auction:
  enabled: true
  allowCreative: false
  cooldown: 60
  minStart: 5
  maxStart: 100000
  Queue:
    maxSize: 10
    maxPerPlayer: 10
  taxAccount: None
  useTaxAccount: false
  startTax: 0
  endTax: 0
  startTaxIsPercent: false
  endTaxIsPercent: true
  taxIfNoBids: false
  notifyTime:
  - 30
  - 10
  - 5
  WorldGroups:
    groups:
    - groupName: Visitor
      enabled: true
      worlds:
      - world
      - world_the_end
      - world_nether
      - Wilderness
      channels: []
    - groupName: Member
      enabled: true
      worlds:
      - world
      - world_the_end
      - world_nether
      - Wilderness
      channels: []
   - groupName: Helper
      enabled: true
      worlds:
      - world
      - world_the_end
      - world_nether
      - Wilderness
      channels: []
   - groupName: Owner
      enabled: true
      worlds:
      - world
      - world_the_end
      - world_nether
      - Wilderness
      channels: []
  Blacklist:
  - Bedrock
  Bidding:
    minIncrement: 100
    maxIncrement: 10000
    defaultTime: 60
    minTime: 30
    maxTime: 120
    snipeTime: 10
    snipeValue: 10
```

---

I also think that there should be color codes in the English.yml and other languages. I know there is color codes but in the Syntax when I try to change it with color codes and doesn't work the color don't show up when I reload the server. It would be great if you can make it so if a person has a nickname (display name) it should show up in the auction instead of there auctual name.

**Comment by Justin42** [comment]
That isn't how world groups work. They do not correspond to permissions in any way. In this case, you should probably remove them all except for one. You also need to be sure that the EXACT name of the world is "Wilderness"

**Comment by ghost** [comment]
Then were do I place it so it works in the world Wilderness?

**Comment by Justin42** [comment]
``` yaml
Main:
  defaultLocale: english
  availableLocale:
  - english
  - french
  - portuguese
Auction:
  enabled: true
  allowCreative: false
  cooldown: 60
  minStart: 5
  maxStart: 100000
  Queue:
    maxSize: 10
    maxPerPlayer: 10
  taxAccount: None
  useTaxAccount: false
  startTax: 0
  endTax: 0
  startTaxIsPercent: false
  endTaxIsPercent: true
  taxIfNoBids: false
  notifyTime:
  - 30
  - 10
  - 5
  WorldGroups:
    groups:
   - groupName: default
      enabled: true
      worlds:
      - world
      - world_the_end
      - world_nether
      - Wilderness
      channels: []
  Blacklist:
  - Bedrock
  Bidding:
    minIncrement: 100
    maxIncrement: 10000
    defaultTime: 60
    minTime: 30
    maxTime: 120
    snipeTime: 10
    snipeValue: 10
```

Whether that will fix your issue, I really don't know. The world names need to be correct, that's the only way to fix your configuration. This is not a bug.
