### ISSUE TITLE
Auction not ending properly.

### ISSUE THREAD

**Issue by ghost** [Justin42/Salesmania#8]
For some reason when I start an auction when the time goes by and the auction is suppose to end it doesn't it just starts another auction and when I do /auction cancel or /auction end it starts the same auction again and when the time ends and someone has already auction and they are suppose to win you do /auction info it says they won but it doesn't give them there items back or it doesn't give me my items back. Also im not sure if this is a bug but I can auction on my own auction.

**Comment by Justin42** [comment]
Please follow these steps exactly:
Stop your server.
Delete your auctionQueue.yml and stash.yml files
Restart your server.

Reply with the EXACT steps to reproduce the issue, your config.yml, and a list of all plugins enabled on your server.

**Comment by ghost** [comment]
I did your steps and for some reason it's still not working.
Ok I've stopped my server deleted the two files and this is my config.yml:

``` yaml
Main:
  defaultLocale: english
  availableLocale:
  - english
  - french
  - portuguese
Auction:
  enabled: true
  allowCreative: false
  cooldown: 60
  minStart: 5
  maxStart: 10000
  Queue:
    maxSize: 10
    maxPerPlayer: 10
  taxAccount: None
  useTaxAccount: false
  startTax: 0
  endTax: 0
  startTaxIsPercent: false
  endTaxIsPercent: true
  taxIfNoBids: false
  notifyTime:
  - 30
  - 10
  - 5
  WorldGroups:
    groups:
    - groupName: default
      enabled: true
      worlds:
      - world
      - world_the_end
      - world_nether
      - Wilderness
      channels: []
  Blacklist:
  - Bedrock
  - Dirt
  - Cobblestone
  - Ender Pearl
  Bidding:
    minIncrement: 100
    maxIncrement: 10000
    defaultTime: 60
    minTime: 30
    maxTime: 120
    snipeTime: 10
    snipeValue: 10
```

My plugin list is:

Worldedit, Nocheatplus, NoDeathMessage, Vanilla, Buycraft, vault, healthbar, permissionsEX, multiverse-core, Logblock, salesmania, LWC, paintball, worldguard, Treeassist, ModReq, AutoMessage, Votifier, Superspleef, GAListener, RandomJoinMessage, PwnFilter, Essentials, EssentialsProtect, EssentialsSpawn, 
Multiverse-Portals, EssentialsAntiBuild, EssentialsChat
